name: Deployment pipeline

env:
  DEPLOYMENT_SKIPPED: ${{ github.event_name != 'push' || contains(join(github.event.commits.*.message) , '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deploy success notification
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' && success() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: Successfully deployed
          message: "**Author:** ${{ github.event.head_commit.author.username }} \n **Commit URL:** ${{ github.event.head_commit.url }}"
          colour: '#34eb67'
      - name: Deploy failure notification
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' && failure() }}
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: Deploy failed
          message: "**Author:** ${{ github.event.head_commit.author.username }} \n **Commit URL:** ${{ github.event.head_commit.url }}"
          colour: '#fa0202'

  tag-release:
    needs: [deployment-pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.DEPLOYMENT_SKIPPED == 'false' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
